server:
  port: 8081

spring:
  application:
    name: scrapper
  grpc:
    server:
      port: 9091
    client:
      default-channel:
        address: static://${APP_BOT_HOST:localhost}:9090
        negotiation-type: plaintext
app:
  bot-client:
    base-url: "http://localhost:8080"
    grpc-channel-name: "bot-channel"
  stackoverflow:
    url: https://api.stackexchange.com/2.3
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}
  github:
    url: https://api.github.com
    token: ${GITHUB_TOKEN}
  scheduler:
    interval: 30s
