server:
  port: 8080

spring:
  application:
    name: bot
  grpc:
    server:
      port: 9090
    client:
      scrapper-channel:
        address: static://${APP_SCRAPPER_HOST:localhost}:9091
        negotiation-type: plaintext

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  scrapper-client:
    base-url: http://localhost:8081
    grpc-channel-name: scrapper-channel
  grpc:
    scrapper-deadline: 5s
  scrapper-client-type: grpc

logging:
  structured:
    format:
      console: logstash
